// generated by edge-codegen — do not edit by hand
// regenerate with: edge-codegen

// Usage: const edge = Edge.create() as unknown as TypedEdge
import type { Edge } from 'edge.js'

export interface EdgeTemplates {
  "components/user-card": {
  displayName: string
  bio: string
}
  "home": {
  user: { name: string }
  posts: { title: string, body: string }[]
  activePage: string
}
  "partials/nav": {
  activePage: string
}
  "profile": {
  user: { displayName: string, bio: string }
  activePage: string
}
}

type UnknownEdgeTemplate<S extends string> = S extends keyof EdgeTemplates ? never : S

export type TypedEdge = Omit<Edge, 'render' | 'renderSync'> & {
  render<K extends keyof EdgeTemplates>(templatePath: K, state: EdgeTemplates[K]): Promise<string>
  render<S extends string>(templatePath: UnknownEdgeTemplate<S>, state?: Record<string, any>): Promise<string>
  renderSync<K extends keyof EdgeTemplates>(templatePath: K, state: EdgeTemplates[K]): string
  renderSync<S extends string>(templatePath: UnknownEdgeTemplate<S>, state?: Record<string, any>): string
}
