import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { findEdgeFiles, templateDocs } from '@edge-language-tools/core'
import { compileTemplates } from './compile.ts'
import {
  collectTemplateDependencies,
  detectSlotNames,
  isClientTemplate,
  type ResolveTemplate,
} from './deps.ts'
import { propsTypeName, renderExportName, slotsTypeName } from './names.ts'
import { validateClientIdentifiers } from './validate.ts'

const RUNTIME_SOURCE = fileURLToPath(new URL('./micro-runtime.ts', import.meta.url))
const HEADER = `// generated by edge-client — do not edit by hand
// regenerate with: edge-client build
`

export interface BuildOptions {
  templatesDir: string
  outDir: string
  format: 'ts' | 'js'
}

export interface BuildResult {
  templates: string[]
  runtimePath: string
  templatesPath: string
}

function templateKey(templatesDir: string, file: string): string {
  return relative(templatesDir, file).replace(/\.edge$/, '').split(sep).join('/')
}

function resolveTemplate(templatesDir: string): ResolveTemplate {
  return (name) => {
    const path = join(templatesDir, `${name.replace(/\./g, '/')}.edge`)
    try {
      return { source: readFileSync(path, 'utf8'), filename: name }
    } catch {
      return null
    }
  }
}

function closureError(offender: string, chain: string[]): string {
  const path = [...chain, offender].join(' <- ')
  return `non-client dependency: ${offender} (chain: ${path})`
}

function collectClosure(
  roots: string[],
  templatesDir: string,
  clientKeys: Set<string>,
  resolve: ResolveTemplate,
): { closure: string[]; error?: string } {
  const visited = new Set<string>()
  const order: string[] = []

  function visit(key: string, chain: string[]): string | null {
    if (visited.has(key)) return null
    visited.add(key)
    const resolved = resolve(key)
    if (!resolved) return `unresolved template: ${key}`
    if (!clientKeys.has(key)) return closureError(key, chain)
    order.push(key)
    for (const dep of collectTemplateDependencies(resolved.source, resolved.filename, resolve)) {
      const err = visit(dep, [...chain, key])
      if (err) return err
    }
    return null
  }

  for (const root of roots.sort()) {
    const err = visit(root, [])
    if (err) return { closure: order, error: err }
  }

  return { closure: order }
}

function runtimeImportExt(format: 'ts' | 'js'): string {
  return format === 'ts' ? './runtime.ts' : './runtime.js'
}

function stripTypesForJs(source: string): string {
  return source
    .replace(/^export type .*$/gm, '')
    .replace(/^export interface [\s\S]*?^}/gm, '')
    .replace(/\breadonly\b/g, '')
    .replace(/: SafeValue/g, '')
    .replace(/: ClientTemplate/g, '')
    .replace(/: CompiledTemplate/g, '')
    .replace(/: Record<string, unknown>/g, '')
    .replace(/: Record<string, CompiledTemplate>/g, '')
    .replace(/: Record<string, \(\) => Promise<string>>/g, '')
    .replace(/: string\[\]/g, '')
    .replace(/: string/g, '')
    .replace(/: number/g, '')
    .replace(/: unknown/g, '')
    .replace(/: Promise<string>/g, '')
    .replace(/<[^>]+>/g, '')
    .replace(/\n{3,}/g, '\n\n')
}

function emitRuntime(outDir: string, format: 'ts' | 'js'): string {
  let source = readFileSync(RUNTIME_SOURCE, 'utf8')
  if (format === 'js') source = stripTypesForJs(source)
  const path = join(outDir, format === 'ts' ? 'runtime.ts' : 'runtime.js')
  writeFileSync(path, `${HEADER}${source.trim()}\n`)
  return path
}

function emitSlotsType(slotNames: string[]): string | null {
  if (slotNames.length === 0) return null
  const members = slotNames.map((name) => `  ${name}?: () => Promise<string>`).join('\n')
  return `{\n${members}\n}`
}

function emitTemplatesModule(
  outDir: string,
  format: 'ts' | 'js',
  entries: {
    key: string
    types: string
    body: string
    slotNames: string[]
  }[],
): string {
  const ext = format === 'ts' ? 'ts' : 'js'
  const importFrom = runtimeImportExt(format)
  const lines: string[] = [HEADER]

  lines.push(`import { createClientTemplate, wrapSlots, type CompiledTemplate } from '${importFrom}'`)
  lines.push('')

  for (const entry of entries) {
    const propsName = propsTypeName(entry.key)
    lines.push(`export type ${propsName} = ${entry.types}`)
    const slots = emitSlotsType(entry.slotNames)
    if (slots) lines.push(`export type ${slotsTypeName(entry.key)} = ${slots}`)
    lines.push('')
  }

  lines.push('const compiled: Record<string, CompiledTemplate> = {')
  for (const entry of entries) {
    lines.push(`  ${JSON.stringify(entry.key)}: async function(template, state, $context) {`)
    for (const line of entry.body.split('\n')) lines.push(`    ${line}`)
    lines.push('  },')
  }
  lines.push('}')
  lines.push('')
  lines.push('const clientTemplate = createClientTemplate(compiled)')
  lines.push('')

  const mapEntries: string[] = []
  for (const entry of entries) {
    const exportName = renderExportName(entry.key)
    const propsName = propsTypeName(entry.key)
    const slotsName = slotsTypeName(entry.key)
    const slotsParam = entry.slotNames.length > 0 ? `, slots?: ${slotsName}` : ''
    lines.push(`export async function ${exportName}(props: ${propsName}${slotsParam}): Promise<string> {`)
    lines.push(`  const slotFns: Record<string, () => Promise<string>> = {}`)
    for (const slot of entry.slotNames) {
      lines.push(`  if (slots?.${slot}) slotFns.${slot} = slots.${slot}`)
    }
    lines.push(`  const state = clientTemplate.getComponentState(`)
    lines.push(`    props as Record<string, unknown>,`)
    lines.push(`    wrapSlots(slotFns),`)
    lines.push(`    { filename: ${JSON.stringify(entry.key)}, line: 1, col: 0 },`)
    lines.push(`  )`)
    lines.push(`  return compiled[${JSON.stringify(entry.key)}](clientTemplate, state, {})`)
    lines.push('}')
    lines.push('')
    mapEntries.push(`  ${JSON.stringify(entry.key)}: ${exportName}`)
  }

  lines.push(`export const templates = {`)
  lines.push(mapEntries.join(',\n'))
  lines.push('} as const')
  lines.push('')

  const path = join(outDir, `templates.${ext}`)
  writeFileSync(path, lines.join('\n'))
  return path
}

export function buildClient(opts: BuildOptions): BuildResult {
  const { templatesDir, outDir, format } = opts
  const resolve = resolveTemplate(templatesDir)
  const files = findEdgeFiles(templatesDir)

  const clientByKey = new Map<string, string>()
  for (const file of files) {
    const source = readFileSync(file, 'utf8')
    const key = templateKey(templatesDir, file)
    if (isClientTemplate(source, key)) clientByKey.set(key, file)
  }

  const roots = [...clientByKey.keys()].sort()
  const clientKeys = new Set(roots)
  const { closure, error } = collectClosure(roots, templatesDir, clientKeys, resolve)
  if (error) throw new Error(error)

  for (const key of closure) {
    const file = clientByKey.get(key)!
    const source = readFileSync(file, 'utf8')
    const docs = templateDocs(source, key)
    if (!docs.types) {
      throw new Error(`@client template ${key} requires a @types block`)
    }
    for (const identError of validateClientIdentifiers(source, key)) {
      throw new Error(
        `${identError.file}:${identError.line}:${identError.col + 1}: unknown identifier '${identError.name}' in @client template`,
      )
    }
  }

  const bodies = compileTemplates(templatesDir, closure)
  const entries = closure.map((key) => {
    const file = clientByKey.get(key)!
    const source = readFileSync(file, 'utf8')
    const docs = templateDocs(source, key)
    return {
      key,
      types: docs.types!,
      body: bodies.get(key)!,
      slotNames: detectSlotNames(bodies.get(key)!),
    }
  })

  mkdirSync(outDir, { recursive: true })
  const runtimePath = emitRuntime(outDir, format)
  const templatesPath = emitTemplatesModule(outDir, format, entries)

  return { templates: closure, runtimePath, templatesPath }
}

export function buildClientOrExit(opts: BuildOptions): number {
  try {
    buildClient(opts)
    return 0
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error))
    return 1
  }
}
