import { readFileSync } from 'node:fs'
import { relative, sep } from 'node:path'
import { findEdgeFiles, generateVirtualTs } from '@edge-language-tools/core'

const HEADER = `// generated by edge-codegen — do not edit by hand
// regenerate with: edge-codegen
`

/** Walks `dir` for \`*.edge\` templates and emits a single \`templates.d.ts\` source string. */
export function generateTemplatesDts(dir: string): string {
  const entries: { key: string; body: string }[] = []

  for (const file of findEdgeFiles(dir)) {
    const source = readFileSync(file, 'utf8')
    const vf = generateVirtualTs(source, file)
    if (!vf.typesBlock) continue

    const key = relative(dir, file).replace(/\.edge$/, '').split(sep).join('/')
    entries.push({ key, body: vf.typesBlock.raw })
  }

  entries.sort((a, b) => a.key.localeCompare(b.key))

  if (entries.length === 0) {
    return `${HEADER}
export interface EdgeTemplates {}
`
  }

  const templateEntries = entries.map((e) => `  ${JSON.stringify(e.key)}: ${e.body}`).join('\n')

  // NOTE: `edge.js`'s Edge class already declares a loose
  // `render(templatePath: string, state?: Record<string, any>)`. TS interface
  // merging can only ADD overloads to a class, never narrow/replace an
  // existing one — so `declare module 'edge.js' { interface Edge { ... } }`
  // would let wrong props for a known template silently match that loose
  // overload. A wrapper type sidesteps this: `Omit` drops the loose members
  // entirely, then the intersection defines both a typed overload (keyed
  // templates) and a fallback overload (unknown templates, any props) with
  // no loose signature left to fall through to.
  return `${HEADER}
// Usage: const edge = Edge.create() as unknown as TypedEdge
import type { Edge } from 'edge.js'

export interface EdgeTemplates {
${templateEntries}
}

type UnknownEdgeTemplate<S extends string> = S extends keyof EdgeTemplates ? never : S

export type TypedEdge = Omit<Edge, 'render' | 'renderSync'> & {
  render<K extends keyof EdgeTemplates>(templatePath: K, state: EdgeTemplates[K]): Promise<string>
  render<S extends string>(templatePath: UnknownEdgeTemplate<S>, state?: Record<string, any>): Promise<string>
  renderSync<K extends keyof EdgeTemplates>(templatePath: K, state: EdgeTemplates[K]): string
  renderSync<S extends string>(templatePath: UnknownEdgeTemplate<S>, state?: Record<string, any>): string
}
`
}
