// generated by edge-codegen — do not edit by hand
// regenerate with: edge-codegen

// Usage: const edge = Edge.create() as unknown as TypedEdge
import type { Edge } from 'edge.js'

export interface EdgeTemplates {
  "components/accordion": {
  multiple?: boolean
  [attr: string]: unknown
}
  "components/alert": {
  variant?: 'default' | 'destructive'
  title?: string
  description?: string
  [attr: string]: unknown
}
  "components/avatar": {
  src?: string
  alt?: string
  fallback?: string
  [attr: string]: unknown
}
  "components/badge": {
  variant?: 'default' | 'secondary' | 'outline' | 'destructive'
  [attr: string]: unknown
}
  "components/breadcrumb": {
  [attr: string]: unknown
}
  "components/button": {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'link' | 'destructive'
  size?: 'xs' | 'sm' | 'lg' | 'icon' | 'icon-xs' | 'icon-sm' | 'icon-lg'
  type?: 'button' | 'submit' | 'reset'
  icon?: 'inline-start' | 'inline-end'
  [attr: string]: unknown
}
  "components/button_group": {
  orientation?: 'horizontal' | 'vertical'
  [attr: string]: unknown
}
  "components/card": {
  size?: 'sm'
  [attr: string]: unknown
}
  "components/chart": {
  type?: 'bar' | 'line' | 'area' | 'pie' | 'donut'
  [attr: string]: unknown
}
  "components/checkbox": {
  name?: string
  value?: string
  checked?: boolean
  disabled?: boolean
  required?: boolean
  id?: string
  label?: string
  [attr: string]: unknown
}
  "components/collapsible": {
  open?: boolean
  [attr: string]: unknown
}
  "components/combobox": {
  id: string
  selected?: string | string[] | { value: string; label?: string } | Array<{ value: string; label?: string }>
  name?: string
  multiple?: boolean
  placeholder?: string
  close_on_select?: boolean
  clear?: boolean
  auto_highlight?: boolean
  format?: 'value' | 'object'
  main_attrs?: Record<string, string>
  input_attrs?: Record<string, string>
  [attr: string]: unknown
}
  "components/command": {
  id: string
  items?: Array<{
    type?: 'item' | 'group' | 'separator'
    label?: string
    url?: string
    icon?: string
    keywords?: string
    disabled?: boolean
    items?: Array<{
      type?: 'item' | 'group' | 'separator'
      label?: string
      url?: string
      icon?: string
      keywords?: string
      disabled?: boolean
    }>
    attrs?: Record<string, string>
    id?: string
  }>
  placeholder?: string
  empty_text?: string
  dialog?: boolean
  open?: boolean
  main_attrs?: Record<string, string>
  input_attrs?: Record<string, string>
  menu_attrs?: Record<string, string>
  dialog_attrs?: Record<string, string>
  [attr: string]: unknown
}
  "components/dialog": {
  id: string
  trigger?: string
  title?: string
  description?: string
  open?: boolean
  close_button?: boolean
  close_on_overlay_click?: boolean
  trigger_attrs?: Record<string, string>
  dialog_attrs?: Record<string, string>
  header_attrs?: Record<string, string>
  body_attrs?: Record<string, string>
  footer_attrs?: Record<string, string>
  [attr: string]: unknown
}
  "components/dropdown_menu": {
  id: string
  items?: Array<{
    type?: 'item' | 'group' | 'separator'
    label?: string
    url?: string
    icon?: string
    items?: Array<{
      type?: 'item' | 'group' | 'separator'
      label?: string
      url?: string
      icon?: string
      attrs?: Record<string, string>
    }>
    attrs?: Record<string, string>
    id?: string
  }>
  trigger_attrs?: Record<string, string>
  main_attrs?: Record<string, string>
  [attr: string]: unknown
}
  "components/empty": {
  title?: string
  description?: string
  [attr: string]: unknown
}
  "components/field": {
  label?: string
  description?: string
  [attr: string]: unknown
}
  "components/form": {
  action?: string
  method?: 'get' | 'post'
  [attr: string]: unknown
}
  "components/input": {
  type?: string
  name?: string
  value?: string
  placeholder?: string
  disabled?: boolean
  required?: boolean
  id?: string
  [attr: string]: unknown
}
  "components/input_group": {
  [attr: string]: unknown
}
  "components/item": {
  title?: string
  description?: string
  [attr: string]: unknown
}
  "components/kbd": {
  [attr: string]: unknown
}
  "components/label": {
  htmlFor?: string
  [attr: string]: unknown
}
  "components/native_select": {
  name?: string
  id?: string
  disabled?: boolean
  required?: boolean
  [attr: string]: unknown
}
  "components/popover": {
  id: string
  trigger_attrs?: Record<string, string>
  popover_attrs?: Record<string, string>
  main_attrs?: Record<string, string>
  [attr: string]: unknown
}
  "components/progress": {
  value?: number
  max?: number
  [attr: string]: unknown
}
  "components/radio": {
  name?: string
  value?: string
  checked?: boolean
  disabled?: boolean
  required?: boolean
  id?: string
  label?: string
  [attr: string]: unknown
}
  "components/scrollbar": {
  [attr: string]: unknown
}
  "components/select": {
  id: string
  selected?: string | string[]
  name?: string
  items?: Array<{
    type?: 'item' | 'group' | 'separator'
    label?: string
    value?: string
    items?: Array<{ label: string; value?: string; attrs?: Record<string, string> }>
    attrs?: Record<string, string>
    id?: string
  }>
  multiple?: boolean
  placeholder?: string
  close_on_select?: boolean
  format?: 'value' | 'object'
  main_attrs?: Record<string, string>
  trigger_attrs?: Record<string, string>
  [attr: string]: unknown
}
  "components/sidebar": {
  id?: string
  label?: string
  open?: boolean
  side?: 'left' | 'right'
  menu?: Array<{
    type?: 'item' | 'group' | 'separator' | 'submenu'
    label?: string
    url?: string
    icon?: string
    current?: boolean
    open?: boolean
    items?: Array<{
      type?: 'item' | 'group' | 'separator' | 'submenu'
      label?: string
      url?: string
      icon?: string
      current?: boolean
      open?: boolean
      items?: unknown[]
    }>
    attrs?: Record<string, string>
    id?: string
  }>
  main_attrs?: Record<string, string>
  [attr: string]: unknown
}
  "components/skeleton": {
  [attr: string]: unknown
}
  "components/switch": {
  name?: string
  checked?: boolean
  disabled?: boolean
  required?: boolean
  id?: string
  label?: string
  [attr: string]: unknown
}
  "components/table": {
  [attr: string]: unknown
}
  "components/tabs": {
  id: string
  tabsets: Array<{
    tab: string
    panel?: string
    tab_attrs?: Record<string, string>
    panel_attrs?: Record<string, string>
  }>
  default_tab_index?: number
  orientation?: 'horizontal' | 'vertical'
  variant?: 'default' | 'line'
  main_attrs?: Record<string, string>
  tablist_attrs?: Record<string, string>
  [attr: string]: unknown
}
  "components/textarea": {
  name?: string
  value?: string
  placeholder?: string
  rows?: number
  disabled?: boolean
  required?: boolean
  id?: string
  [attr: string]: unknown
}
  "components/toast": {
  id?: string
  toasts?: Array<{
    category?: 'success' | 'error' | 'info' | 'warning'
    title?: string
    description?: string
    duration?: number
    action?: { label: string; onclick?: string; href?: string }
    cancel?: { label: string; onclick?: string; href?: string }
    attrs?: Record<string, string>
  }>
  category?: 'success' | 'error' | 'info' | 'warning'
  title?: string
  description?: string
  duration?: number
  action?: { label: string; onclick?: string; href?: string }
  cancel?: { label: string; onclick?: string; href?: string }
  attrs?: Record<string, string>
  [attr: string]: unknown
}
  "components/tooltip": {
  id: string
  [attr: string]: unknown
}
}

type UnknownEdgeTemplate<S extends string> = S extends keyof EdgeTemplates ? never : S

export type TypedEdge = Omit<Edge, 'render' | 'renderSync'> & {
  render<K extends keyof EdgeTemplates>(templatePath: K, state: EdgeTemplates[K]): Promise<string>
  render<S extends string>(templatePath: UnknownEdgeTemplate<S>, state?: Record<string, any>): Promise<string>
  renderSync<K extends keyof EdgeTemplates>(templatePath: K, state: EdgeTemplates[K]): string
  renderSync<S extends string>(templatePath: UnknownEdgeTemplate<S>, state?: Record<string, any>): string
}
